language: php

php:
  - 5.3

env:
  - DB=mysql

before_script:
  - mysql -e 'CREATE DATABASE cakephp_test;';
  - mv  Config/database.travis.php Config/database.php

script:
  - ./Console/cake test Test/Case/AllTest.php  --stderr